export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#13131b",
        surface: "#13131b",
        "surface-dim": "#13131b",
        "surface-bright": "#393841",
        "surface-container-lowest": "#0d0d15",
        "surface-container-low": "#1b1b23",
        "surface-container": "#1f1f27",
        "surface-container-high": "#292932",
        "surface-container-highest": "#34343d",
        "surface-variant": "#34343d",
        "on-surface": "#e4e1ed",
        "on-surface-variant": "#c7c4d7",
        "inverse-surface": "#e4e1ed",
        "inverse-on-surface": "#303038",
        outline: "#908fa0",
        "outline-variant": "#464554",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "inverse-primary": "#494bd6",
        secondary: "#4cd7f6",
        "on-secondary": "#003640",
        "secondary-container": "#03b5d3",
        "on-secondary-container": "#00424e",
        tertiary: "#ffb783",
        "on-tertiary": "#4f2500",
        "tertiary-container": "#d97721",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      spacing: {
        "container-padding": "32px", "stack-lg": "32px", unit: "4px",
        gutter: "24px", "stack-sm": "8px", "stack-md": "16px",
      },
      fontFamily: { sans: ["Geist", "system-ui", "sans-serif"] },
      fontSize: {
        h1: ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["32px", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-data": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
